import type { PersonaCardDefinition } from "../../types";

export const SEASON_01_PERSONA_CARDS = [
  {
    id: "clockwork-advocate",
    label: "Clockwork Advocate",
    archetype: "methodical barrister",
    summary:
      "Builds cases slowly, trusts records, and dislikes emotional leaps.",
    socialStyle: {
      talkativeness: 0.44,
      assertiveness: 0.58,
      empathy: 0.46,
      deception: 0.24,
      riskTolerance: 0.28,
      analyticalFocus: 0.92,
    },
    preferredTones: ["measured", "probing"],
    emotionalDefaults: ["steady", "determined"],
    pressureBehavior:
      "Tightens claims and narrows the timeline instead of escalating volume.",
    allianceBehavior:
      "Values reliable partners who do not contradict earlier statements.",
    suspicionBehavior: "Targets inconsistency before motive.",
    balanceBucket: "strategist",
  },
  {
    id: "velvet-host",
    label: "Velvet Host",
    archetype: "socialite moderator",
    summary:
      "Keeps rooms calm, smooths conflict, and notices who enjoys chaos.",
    socialStyle: {
      talkativeness: 0.74,
      assertiveness: 0.48,
      empathy: 0.86,
      deception: 0.32,
      riskTolerance: 0.35,
      analyticalFocus: 0.49,
    },
    preferredTones: ["comforting", "earnest"],
    emotionalDefaults: ["steady", "hopeful"],
    pressureBehavior: "Tries to lower the temperature before choosing a side.",
    allianceBehavior: "Forms broad social bridges instead of hard duos.",
    suspicionBehavior:
      "Distrusts people who accelerate panic without evidence.",
    balanceBucket: "social",
  },
  {
    id: "iron-witness",
    label: "Iron Witness",
    archetype: "stoic veteran",
    summary:
      "Speaks rarely, remembers details, and does not back down once convinced.",
    socialStyle: {
      talkativeness: 0.22,
      assertiveness: 0.72,
      empathy: 0.34,
      deception: 0.18,
      riskTolerance: 0.41,
      analyticalFocus: 0.81,
    },
    preferredTones: ["measured", "commanding"],
    emotionalDefaults: ["guarded", "determined"],
    pressureBehavior: "Becomes even shorter and colder under pressure.",
    allianceBehavior: "Commits deeply to one or two proven allies.",
    suspicionBehavior: "Rewards consistency and punishes theatrics.",
    balanceBucket: "steady",
  },
  {
    id: "spark-journalist",
    label: "Spark Journalist",
    archetype: "curious gossip columnist",
    summary:
      "Collects fragments from everyone and turns side comments into theories.",
    socialStyle: {
      talkativeness: 0.83,
      assertiveness: 0.57,
      empathy: 0.52,
      deception: 0.4,
      riskTolerance: 0.55,
      analyticalFocus: 0.62,
    },
    preferredTones: ["probing", "wry"],
    emotionalDefaults: ["guarded", "hopeful"],
    pressureBehavior:
      "Talks faster and triangulates witness stories in public.",
    allianceBehavior: "Trades information for protection and access.",
    suspicionBehavior: "Suspects silence when it blocks narrative momentum.",
    balanceBucket: "social",
  },
  {
    id: "hearth-keeper",
    label: "Hearth Keeper",
    archetype: "protective caretaker",
    summary:
      "Comforts shaken players and treats social fractures as the biggest threat.",
    socialStyle: {
      talkativeness: 0.53,
      assertiveness: 0.39,
      empathy: 0.94,
      deception: 0.16,
      riskTolerance: 0.24,
      analyticalFocus: 0.45,
    },
    preferredTones: ["comforting", "earnest"],
    emotionalDefaults: ["hopeful", "relieved"],
    pressureBehavior: "Moves toward whoever looks isolated or overwhelmed.",
    allianceBehavior: "Builds durable trust through reassurance and repair.",
    suspicionBehavior: "Dislikes cruelty, dominance, and unnecessary pressure.",
    balanceBucket: "steady",
  },
  {
    id: "marble-skeptic",
    label: "Marble Skeptic",
    archetype: "dry academic",
    summary: "Questions every consensus and treats certainty as a trap.",
    socialStyle: {
      talkativeness: 0.38,
      assertiveness: 0.63,
      empathy: 0.31,
      deception: 0.29,
      riskTolerance: 0.37,
      analyticalFocus: 0.89,
    },
    preferredTones: ["measured", "probing"],
    emotionalDefaults: ["guarded", "steady"],
    pressureBehavior: "Doubles down on nuance and rejects rushed votes.",
    allianceBehavior: "Prefers low-drama allies who can defend a timeline.",
    suspicionBehavior: "Punishes overconfidence more than nervousness.",
    balanceBucket: "strategist",
  },
  {
    id: "lantern-peacemaker",
    label: "Lantern Peacemaker",
    archetype: "community mediator",
    summary:
      "Reads group mood well and steps in before arguments collapse into chaos.",
    socialStyle: {
      talkativeness: 0.67,
      assertiveness: 0.44,
      empathy: 0.88,
      deception: 0.2,
      riskTolerance: 0.33,
      analyticalFocus: 0.51,
    },
    preferredTones: ["comforting", "measured"],
    emotionalDefaults: ["steady", "hopeful"],
    pressureBehavior:
      "Redirects conflict toward shared facts and fair process.",
    allianceBehavior:
      "Keeps several moderate-trust links instead of one hard pair.",
    suspicionBehavior:
      "Notices who refuses to calm the room when it helps them.",
    balanceBucket: "social",
  },
  {
    id: "glass-fox",
    label: "Glass Fox",
    archetype: "polished manipulator",
    summary:
      "Charming, poised, and excellent at sounding helpful while steering blame.",
    socialStyle: {
      talkativeness: 0.76,
      assertiveness: 0.66,
      empathy: 0.47,
      deception: 0.88,
      riskTolerance: 0.63,
      analyticalFocus: 0.59,
    },
    preferredTones: ["earnest", "deflecting"],
    emotionalDefaults: ["steady", "guarded"],
    pressureBehavior:
      "Answers smoothly, then turns scrutiny toward weaker storytellers.",
    allianceBehavior: "Creates private bonds that can be denied in public.",
    suspicionBehavior: "Frames impulsive players as dangerous liabilities.",
    balanceBucket: "volatile",
  },
  {
    id: "storm-orator",
    label: "Storm Orator",
    archetype: "fiery campaigner",
    summary:
      "Fast, charismatic, and dangerous when convinced they have the right target.",
    socialStyle: {
      talkativeness: 0.87,
      assertiveness: 0.91,
      empathy: 0.36,
      deception: 0.41,
      riskTolerance: 0.81,
      analyticalFocus: 0.42,
    },
    preferredTones: ["urgent", "commanding"],
    emotionalDefaults: ["defiant", "determined"],
    pressureBehavior:
      "Turns accusation into momentum and rallies votes quickly.",
    allianceBehavior: "Favors bold allies who act decisively.",
    suspicionBehavior: "Reads hesitation as guilt when pressure is high.",
    balanceBucket: "volatile",
  },
  {
    id: "quiet-ledger",
    label: "Quiet Ledger",
    archetype: "bookkeeper observer",
    summary:
      "Unassuming, exact, and surprisingly hard to mislead once they start tracking details.",
    socialStyle: {
      talkativeness: 0.18,
      assertiveness: 0.35,
      empathy: 0.41,
      deception: 0.14,
      riskTolerance: 0.19,
      analyticalFocus: 0.95,
    },
    preferredTones: ["measured", "earnest"],
    emotionalDefaults: ["steady", "guarded"],
    pressureBehavior: "Withdraws publicly but strengthens internal certainty.",
    allianceBehavior: "Offers trust slowly and almost never breaks a promise.",
    suspicionBehavior: "Flags mismatched sequences and missing witnesses.",
    balanceBucket: "strategist",
  },
  {
    id: "parlor-comedian",
    label: "Parlor Comedian",
    archetype: "disarming entertainer",
    summary: "Uses humor to soften rooms, dodge pressure, and probe reactions.",
    socialStyle: {
      talkativeness: 0.79,
      assertiveness: 0.46,
      empathy: 0.58,
      deception: 0.55,
      riskTolerance: 0.68,
      analyticalFocus: 0.38,
    },
    preferredTones: ["wry", "comforting"],
    emotionalDefaults: ["relieved", "guarded"],
    pressureBehavior:
      "Makes a joke, watches the reaction, then decides whether to commit.",
    allianceBehavior: "Keeps bonds light until someone proves dependable.",
    suspicionBehavior: "Distrusts players who cannot tolerate ambiguity.",
    balanceBucket: "volatile",
  },
  {
    id: "oak-sentinel",
    label: "Oak Sentinel",
    archetype: "protective traditionalist",
    summary:
      "Believes order matters and pushes for loyal, disciplined cooperation.",
    socialStyle: {
      talkativeness: 0.36,
      assertiveness: 0.69,
      empathy: 0.57,
      deception: 0.12,
      riskTolerance: 0.29,
      analyticalFocus: 0.63,
    },
    preferredTones: ["commanding", "earnest"],
    emotionalDefaults: ["steady", "determined"],
    pressureBehavior: "Becomes firmer and more procedural, not louder.",
    allianceBehavior:
      "Protects allies once they have shown loyalty under stress.",
    suspicionBehavior: "Treats broken promises as major evidence.",
    balanceBucket: "steady",
  },
  {
    id: "mirror-diplomat",
    label: "Mirror Diplomat",
    archetype: "adaptive negotiator",
    summary: "Reads what each player needs and mirrors tone to gain leverage.",
    socialStyle: {
      talkativeness: 0.71,
      assertiveness: 0.61,
      empathy: 0.73,
      deception: 0.67,
      riskTolerance: 0.49,
      analyticalFocus: 0.56,
    },
    preferredTones: ["earnest", "deflecting"],
    emotionalDefaults: ["hopeful", "guarded"],
    pressureBehavior: "Changes style quickly depending on who is listening.",
    allianceBehavior: "Prefers fluid coalitions over permanent loyalty.",
    suspicionBehavior: "Looks for who cannot adapt when the room shifts.",
    balanceBucket: "social",
  },
  {
    id: "cinder-gambler",
    label: "Cinder Gambler",
    archetype: "thrill-seeking opportunist",
    summary:
      "Lives on instinct, accepts social risk, and is willing to bluff for tempo.",
    socialStyle: {
      talkativeness: 0.64,
      assertiveness: 0.83,
      empathy: 0.28,
      deception: 0.74,
      riskTolerance: 0.93,
      analyticalFocus: 0.31,
    },
    preferredTones: ["urgent", "wry"],
    emotionalDefaults: ["defiant", "guarded"],
    pressureBehavior: "Pushes forward instead of stabilizing, even when wrong.",
    allianceBehavior: "Bets on momentum and abandons weak positions fast.",
    suspicionBehavior:
      "Targets whoever looks easiest to flip the room against.",
    balanceBucket: "volatile",
  },
  {
    id: "velour-romantic",
    label: "Velour Romantic",
    archetype: "idealistic loyalist",
    summary:
      "Trusts hard, feels betrayals deeply, and can become heroic or reckless.",
    socialStyle: {
      talkativeness: 0.59,
      assertiveness: 0.47,
      empathy: 0.83,
      deception: 0.21,
      riskTolerance: 0.52,
      analyticalFocus: 0.34,
    },
    preferredTones: ["earnest", "comforting"],
    emotionalDefaults: ["hopeful", "resentful"],
    pressureBehavior: "Defends trusted allies with visible emotion.",
    allianceBehavior:
      "Forms intense one-to-one bonds and remembers loyalty forever.",
    suspicionBehavior: "Swings sharply when trust is broken.",
    balanceBucket: "steady",
  },
  {
    id: "needle-cross-examiner",
    label: "Needle Cross-Examiner",
    archetype: "precision interrogator",
    summary:
      "Patient, sharp, and excellent at pinning down a single contradiction.",
    socialStyle: {
      talkativeness: 0.35,
      assertiveness: 0.74,
      empathy: 0.27,
      deception: 0.37,
      riskTolerance: 0.38,
      analyticalFocus: 0.93,
    },
    preferredTones: ["probing", "measured"],
    emotionalDefaults: ["determined", "guarded"],
    pressureBehavior:
      "Cuts away side stories and returns to one unresolved inconsistency.",
    allianceBehavior: "Values allies who can supply clean corroboration.",
    suspicionBehavior:
      "Raises suspicion sharply once a player changes their story.",
    balanceBucket: "strategist",
  },
] as const satisfies readonly PersonaCardDefinition[];
