import type { SabotageTypeDefinition } from "../../types";

export const SEASON_01_SABOTAGE_TYPES = [
  {
    id: "blackout",
    actionId: "trigger-blackout",
    label: "Trigger blackout",
    summary: "Drop the manor into darkness and muddy witness timelines.",
    targetKind: "global",
    durationSeconds: 18,
    cooldownSeconds: 45,
    visibility: "public",
    evidenceTags: ["darkness", "panic", "timing"],
  },
  {
    id: "jam-door",
    actionId: "jam-door",
    label: "Jam a door",
    summary: "Lock down a room route and isolate or delay a witness.",
    targetKind: "room",
    durationSeconds: 20,
    cooldownSeconds: 35,
    visibility: "suspicious",
    evidenceTags: ["door", "delay", "trap"],
  },
  {
    id: "loop-cameras",
    actionId: "loop-cameras",
    label: "Loop cameras",
    summary:
      "Replay stale footage in Surveillance Hall to create false certainty.",
    targetKind: "room",
    durationSeconds: 16,
    cooldownSeconds: 40,
    visibility: "stealth",
    evidenceTags: ["surveillance", "deception", "timing"],
  },
  {
    id: "forge-ledger-entry",
    actionId: "forge-ledger-entry",
    label: "Forge ledger entry",
    summary: "Insert a false paper trail around a task or room visit.",
    targetKind: "task",
    durationSeconds: 30,
    cooldownSeconds: 42,
    visibility: "stealth",
    evidenceTags: ["ledger", "paper-trail", "forgery"],
  },
  {
    id: "plant-false-clue",
    actionId: "plant-false-clue",
    label: "Plant false clue",
    summary:
      "Leave misleading evidence where an innocent player is likely blamed.",
    targetKind: "room",
    durationSeconds: 30,
    cooldownSeconds: 40,
    visibility: "stealth",
    evidenceTags: ["clue", "misdirection", "frame-job"],
  },
  {
    id: "mimic-task-audio",
    actionId: "mimic-task-audio",
    label: "Mimic task audio",
    summary: "Fake a task sound cue to support a false alibi.",
    targetKind: "task",
    durationSeconds: 12,
    cooldownSeconds: 28,
    visibility: "suspicious",
    evidenceTags: ["audio", "alibi", "misdirection"],
  },
  {
    id: "delay-two-person-task",
    actionId: "delay-two-person-task",
    label: "Delay two-person task",
    summary: "Break a cooperation chain and force allies to split or linger.",
    targetKind: "task",
    durationSeconds: 22,
    cooldownSeconds: 38,
    visibility: "stealth",
    evidenceTags: ["cooperation", "delay", "friction"],
  },
] as const satisfies readonly SabotageTypeDefinition[];
